host: horses.farm:*
fullnameOverride: horses-app

image:
  repository: hashicorp/http-echo
  tag: "1.0"

containerPort: 5678

config:
  ECHO_TEXT: "Hello from Horses!!! VERSION 3"

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - horses
        topologyKey: kubernetes.io/hostname

rollout:
  enabled: true
  revisionHistoryLimit: 5
  strategy:
    canary:
      stableService: horses-app
      canaryService: horses-app-preview
      trafficRouting:
        ambassador:
          mappings:
            - horses-app-mapping
      steps:
        - setWeight: 25
        - pause:
            duration: 30s
        - setWeight: 50
        - pause:
            duration: 30s
        - setWeight: 90
        - pause: {}