host: catsv2.farm:8080
fullnameOverride: cats-app

config:
  ECHO_TEXT: "Hello from Cats!!!zz!"

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - cats
        topologyKey: kubernetes.io/hostname