host: cats.farm:*
fullnameOverride: cats-app

config:
  ECHO_TEXT: "Hello from Cats!!!"

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - cats
        topologyKey: kubernetes.io/hostname

rollout:
  enabled: true
  revisionHistoryLimit: 5
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause:
            duration: 30s
        - setWeight: 50
        - pause:
            duration: 30s