host: dogsv2.farm:8080
fullnameOverride: dogs-app

config:
  ECHO_TEXT: "Hello from Dogs!!!"

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - dogs
          topologyKey: kubernetes.io/hostname