host: dogs.farm:*
fullnameOverride: dogs-app

config:
  ECHO_TEXT: "Hello from Dogs!!!"

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - dogs
        topologyKey: kubernetes.io/hostname