host: cats.farm:8080
fullnameOverride: cats-app

config:
  HELLO_MSG: "Hello from Cats!!!"

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
        podAffinityTerm:
          labelSelector:
            matchExpressions:
                values:
                  - cats