host: horses.farm:*
fullnameOverride: horses-app

image:
  repository: hashicorp/http-echo

config:
  ECHO_TEXT: "Hello from Horses!!! VERSION 1"

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - horses
        topologyKey: kubernetes.io/hostname

rollout:
  enabled: true
  revisionHistoryLimit: 5
  strategy:
    canary:
      stableService: horses-app
      canaryService: horses-preview
      trafficRouting:
        ambassador:
          mappings:
            - horses-app-mapping
      steps:
        - setWeight: 25
        - pause:
            duration: 30s
        - setWeight: 50
        - pause:
            duration: 30s
        - setWeight: 90
        - pause: {}