environment: dev

image:
  repository: mendhak/http-https-echo
  pullPolicy: Always
  tag: "latest"

replicas: 2

probePath: /

resources:
  limits:
    memory: 48Mi
  requests:
    cpu: 5m
    memory: 24Mi

config:
  ENVIRONMENT: dev

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

port: 80
containerPort: 8080

ingress:
  timeout_ms: 30000

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - app
        topologyKey: kubernetes.io/hostname

rollout:
  enabled: false
  revisionHistoryLimit: 5
  # strategy:
  #   canary:
  #     steps:
  #       - setWeight: 25
  #       - pause:
  #           duration: 30s
  #       - setWeight: 50
  #       - pause:
  #           duration: 30s