{{- if .Values.grafana.enabled }}
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: grafana-mapping
  labels:
    {{- include "farm-application.labels" . | nindent 4 }}
  annotations:
    {{- include "farm-application.annotations" . | nindent 4 }}
spec:
  hostname: {{ .Values.grafana.hostname }}
  prefix: /
  service: prometheus-stack-grafana.platform:80
  timeout_ms: 30000
  connect_timeout_ms: 30000
{{- end }}

{{- if .Values.prometheus.enabled }}
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: prom-mapping
  labels:
    {{- include "farm-application.labels" . | nindent 4 }}
  annotations:
    {{- include "farm-application.annotations" . | nindent 4 }}
spec:
  hostname: {{ .Values.prometheus.hostname }}
  prefix: /
  service: prometheus-stack-kube-prom-prometheus:9090
  timeout_ms: 30000
  connect_timeout_ms: 30000
{{- end }}