{{ $dot := . }}
{{- if .Values.createRepoSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: github-repo-creds
  namespace: {{ .Values.namespace }}
  labels:
    argocd.argoproj.io/secret-type: repo-creds
    {{- include "farm-application.labels" . | nindent 4 }}
  annotations:
    {{- include "farm-application.annotations" . | nindent 4 }}
stringData:
  type: git
  url: https://github.com/pixelari
  password: {{ .Values.repoPAT }}
  username: pixelari
{{- end }}
