{{- if .Values.ingress.enabled }}
---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: http-8080
  labels:
    name: http-8080
    ingress: basic-http
    {{- include "farm-application.labels" . | nindent 4 }}
  annotations:
    {{- include "farm-application.annotations" . | nindent 4 }}
spec:
  port: 8080
  protocol: HTTP
  securityModel: XFP
  hostBinding:
    namespace:
      from: ALL
---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: https-8443
  labels:
    name: https-8443
    ingress: basic-https
    {{- include "farm-application.labels" . | nindent 4 }}
  annotations:
    {{- include "farm-application.annotations" . | nindent 4 }}
spec:
  port: 8443
  protocol: HTTPS
  securityModel: XFP
  hostBinding:
    namespace:
      from: ALL
{{- end }}
