{{- if .Values.localCa.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zedge-ca
  labels:
    {{- include "zedge-application.labels" . | nindent 4 }}
  annotations:
    {{- include "zedge-application.annotations" . | nindent 4 }}
  namespace: {{ .Values.localCa.namespace }}
spec:
  isCA: true
  commonName: "{{ .Values.localCa.domain }} Root CA"
  secretName: zedge-ca-keypair
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  duration: 8760h
  privateKey:
    algorithm: RSA
    size: 2048
{{- end }}