{{- if .Values.localCert.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.localCert.name }}
  namespace: {{ .Values.localCa.namespace }}
  labels:
    {{- include "farm-application.labels" . | nindent 4 }}
  annotations:
    {{- include "farm-application.annotations" . | nindent 4 }}
spec:
  secretName: {{ .Values.localCert.secretName }}
  dnsNames:
    - "*.{{ .Values.domain }}"
  commonName: "*.{{ .Values.domain }}"
  subject:
    organizations:
      - "{{ .Values.domain | title }} Org"
    organizationalUnits:
      - "Platform Team"
    countries:
      - "LT"
  issuerRef:
    name: {{ .Values.localCa.issuerName }}
    kind: ClusterIssuer
  duration: {{ .Values.localCert.duration }}
  renewBefore: {{ .Values.localCert.renewBefore }}
{{- end }}