{{- if .Values.localCert.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.localCert.name }}
  namespace: {{ .Values.localCa.namespace }}
  labels:
    {{- include "zedge-application.labels" . | nindent 4 }}
  annotations:
    {{- include "zedge-application.annotations" . | nindent 4 }}
spec:
  secretName: {{ .Values.localCert.secretName }}
  dnsNames:
    - "*.{{ .Values.localCert.domain }}"
  issuerRef:
    name: {{ .Values.localCa.issuerName }}
    kind: ClusterIssuer
  duration: {{ .Values.localCert.duration }}
  renewBefore: {{ .Values.localCert.renewBefore }}
{{- end }}