---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "farm-application.fullname" . }}-config
  labels:
    {{- include "farm-application.labels" . | nindent 4 }}
  annotations:
    {{- include "farm-application.annotations" . | nindent 4 }}
data:
{{- range $key, $val := .Values.config }}
  {{ $key }}: {{ $val | quote }}
{{- end }}