---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: {{ include "farm-application.fullname" . }}-mapping
  namespace: emissary
spec:
  hostname: {{ .Values.host }}
  prefix: /
  service: {{ include "farm-application.fullname" . }}.default.svc
  timeout_ms: {{ .Values.ingress.timeout_ms }}