---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "farm-application.fullname" . }}-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ include "farm-application.fullname" . }}