---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "farm-application.fullname" . }}
spec:
  selector:
    app: {{ include "farm-application.fullname" . }}
  ports:
    - port: {{ .Values.containerPort }}
      targetPort: {{ .Values.port }}