apiVersion: v2
name: farm-prometheus
description: A Helm chart for Farm Prometheus deployment.
type: application
version: 0.1.0
dependencies:
  - name: kube-prometheus-stack
    version: 73.2.0
    repository: https://prometheus-community.github.io/helm-charts
